from setuptools import setup


setup(name = 'GuJo',
      version = '0.0',
      description = 'DUNE ND Geometries generated by GGD',
      author = 'Jose Palomino and Guang Yang',
      author_email = 'gyang@nngroup.physics.sunysb.edu',
      license = 'GPLv2',
      url = 'https://github.com/gyang9/GuJo',
      #package_dir = {'':'python'},
      package_dir = {},
      packages = ['dunend', 'dunend.ID'],
      install_requires = [
        "gegede >= 0.4",
        "pint >= 0.5.1",      # for units
        "lxml >= 3.3.5",      # for GDML export],
      ],
      #install_requires = [l for l in open("requirements.txt").readlines() if l.strip()],
      # implicitly depends on ROOT
              
  )

